### ISSUE TITLE
Awesome found some

### ISSUE THREAD

**Issue by sri-sanath** [panch0r3d/nuclei-templates#1]
Thank you bro your header sqli worked like a cham if possible can you make more

**Comment by panch0r3d** [comment]
That's awesome!!! I haven't even found any yet with that one :) Yes I'll get more out as I get ideas and get them coded but if you have any suggestions on new ones definitely shoot them my way and I'll see what I can do.

**Comment by sri-sanath** [comment]
Sure bro
